services:
  app:
    build: .
    container_name: isi-burger-app
    ports:
      - "8081:80"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_DATABASE=isi_burger_db
      - DB_USERNAME=sail
      - DB_PASSWORD=password
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: isi-burger-db
    environment:
      - POSTGRES_DB=isi_burger
      - POSTGRES_USER=sail
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: isi-burger-redis

volumes:
  db_data: